### PR TITLE
adds some unit tests and capitalization of all acronyms

### PR DESCRIPTION
**Pull request by willmadison**

### CODE REVIEW

**Comment by willmadison** [comment]
@astevens009 what do you think? Any suggestions for ways to make this pull request better?

**Comment by willmadison** [comment]
@astevens009 think we'll be able to get these changes merged in? Totally cool if not just didn't want to leave the PR dangling :)

**Comment by astevens009** [comment]
@willmadison : Sorry for the delay in getting back to you (I'm still learning my way 'round GitHub :) ). While I appreciate your input, the goal of my portfolio, at this time, is to:

1.  demonstrate my skills
2.  get feedback, through hints or recommended resources (without contributors actually doing the work for me)
3.  get recommendations for ways to improve the code

I've found that is the best way for me to learn.

**Comment by willmadison** [comment]
Duly noted. Thanks for following up. Closing.

**Comment by willmadison** [comment]
To your goal of looking for feedback without source contributions my primary feedback is two-fold:

1. Always include unit tests that test for the behavior of what it is you're implementing. This will help you be able to move speedily with a safety net to catch any mistakes you make along the way.
2. Consider the CLI (Command Line Interface) a consumer/client of an application programming interface or set of methods that solves the cored problem you're out to solve. This is a good practice to have in general because quite often the core business logic of a given problem is, or should be, modular enough that it could be exposed through multiple avenues and contexts (i.e. a Web Service/API, Command Line Application, etc.) but if some of the business logic is fragmented in the client (in this case the main method of the command line interface) this is harder to accomplish.

**Comment by astevens009** [comment]
Thank you for the feedback. The courses I'm reviewing haven't covered testing yet, but I will do some research on my own to learn more about this.

**Pull request closed without merging**
